<?php

namespace AuditTool\PDF;

use Michelf\MarkdownExtra;

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

/**
 * Turns the AI Markdown audit into HTML ready for Dompdf,
 * and injects screenshot URLs (generated by the Node/Playwright worker)
 * into the final HTML.
 *
 * Layout focus:
 * - Clean header with meta (no big "Visitor Report" title line).
 * - NO global "Key screenshots" section at the top.
 * - Screenshots are injected in compact blocks directly under
 *   the most relevant category headings based on group_id:
 *     - UX_MESSAGING  -> UX / Navigation / Messaging / Brand / Trust sections
 *     - VISIBILITY    -> SEO / Content / Performance / Mobile sections
 *     - AUTHORITY     -> Social / GBP / Reviews / Authority / Legal sections
 * - Each block:
 *     - Uses only the client-friendly "purpose" text as caption.
 *     - Hides internal "notes" and "group_id".
 *     - Keeps images in correct aspect ratio (no squashing).
 * - Existing Markdown image placeholders:
 *     ![Label](screenshot:SHOT_ID)
 *   still work and are converted to real <img> tags.
 */
class Markdown_Renderer {

    /**
     * Render full HTML document from Markdown.
     *
     * @param string $markdown
     * @param string $website_url
     * @param array  $meta {
     *   @type string $name        Owner name (optional).
     *   @type string $audit_id    Audit ID (e.g. AR-0123).
     *   @type string $report_type "Visitor Report" | "Owner Report" (metadata only).
     *   @type string $contact_url Contact URL.
     *   @type string $date        Report date (d-m-Y).
     * }
     *
     * @return string
     */
    public function render( string $markdown, string $website_url = '', array $meta = [] ): string {
        $inner_html = $this->render_html( $markdown, $website_url, $meta );
        return $this->wrap_html( $inner_html, $website_url, $meta );
    }

    /**
     * Convert Markdown body into HTML, handling screenshot placeholders and
     * injecting grouped screenshots under relevant headings.
     *
     * @param string $markdown
     * @param string $website_url
     * @param array  $meta
     *
     * @return string HTML fragment (no <html>/<body> wrapper)
     */
    public function render_html( string $markdown, string $website_url = '', array $meta = [] ): string {
        // 1) Replace screenshot:ID placeholders with real image URLs when available.
        $markdown = $this->transform_screenshot_placeholders( $markdown, $website_url, $meta );

        // 2) Markdown -> HTML.
        if ( class_exists( MarkdownExtra::class ) ) {
            $html = MarkdownExtra::defaultTransform( $markdown );
        } else {
            // Fallback: very simple, should not normally be used.
            $html = nl2br( esc_html( $markdown ) );
            return $html; // Do not attempt complex injection in this rare fallback.
        }

        // 3) Inject grouped screenshots directly under the most relevant headings.
        $html = $this->inject_group_screenshots_into_html( $html, $meta );

        return $html;
    }

    /**
     * Transform any Markdown screenshot placeholders into real image URLs when possible.
     *
     * Supported syntax:
     *   ![Homepage hero](screenshot:HOME_HERO)
     *
     * If a screenshot with id "HOME_HERO" exists in:
     *   option: audit_tool_screenshots_{audit_id}
     * we rewrite the Markdown to:
     *   ![Homepage hero](https://46.224.119.20/audits/shot-....jpg)
     *
     * If no screenshot data exists yet, we strip the image and keep only the label text.
     *
     * @param string $markdown
     * @param string $website_url
     * @param array  $meta
     *
     * @return string
     */
    private function transform_screenshot_placeholders( string $markdown, string $website_url = '', array $meta = [] ): string {
        $audit_id = isset( $meta['audit_id'] ) ? trim( (string) $meta['audit_id'] ) : '';

        if ( '' === $audit_id ) {
            // Nothing to map against; just remove the placeholder URLs.
            return (string) preg_replace(
                '/!\[(.*?)\]\((screenshot:([^)\r\n]+))\)/i',
                '$1',
                $markdown
            );
        }

        $key    = 'audit_tool_screenshots_' . $audit_id;
        $stored = get_option( $key, [] );

        if ( ! is_array( $stored ) || empty( $stored ) ) {
            // No screenshots stored yet; strip the markdown images and keep labels.
            return (string) preg_replace(
                '/!\[(.*?)\]\((screenshot:([^)\r\n]+))\)/i',
                '$1',
                $markdown
            );
        }

        // Build an index of id => image_url from stored data.
        $index = [];
        foreach ( $stored as $shot_id => $info ) {
            if ( ! empty( $info['image_url'] ) ) {
                $index[ (string) $shot_id ] = (string) $info['image_url'];
            }
        }

        if ( empty( $index ) ) {
            return $markdown;
        }

        return (string) preg_replace_callback(
            '/!\[(.*?)\]\((screenshot:([^)\r\n]+))\)/i',
            function ( $matches ) use ( $index ) {
                $label = trim( (string) $matches[1] );
                $id    = trim( (string) $matches[3] );

                if ( isset( $index[ $id ] ) && '' !== $index[ $id ] ) {
                    $safe_label = $label !== '' ? $label : 'Screenshot';
                    $safe_url   = esc_url( $index[ $id ] );

                    return '![' . $safe_label . '](' . $safe_url . ')';
                }

                // If no URL for this screenshot, fall back to just the label.
                return $label !== '' ? $label : '';
            },
            $markdown
        );
    }

    /**
     * Wrap converted Markdown in a full HTML document:
     * - Header / summary card.
     * - Main audit content (already has screenshots injected under headings).
     *
     * @param string $content_html Already-converted Markdown HTML.
     * @param string $website_url
     * @param array  $meta
     *
     * @return string Full HTML document.
     */
    private function wrap_html( string $content_html, string $website_url = '', array $meta = [] ): string {
        $website_url = trim( (string) $website_url );
        $name        = isset( $meta['name'] ) ? (string) $meta['name'] : '';
        $audit_id    = isset( $meta['audit_id'] ) ? (string) $meta['audit_id'] : '';
        $report_type = isset( $meta['report_type'] ) ? (string) $meta['report_type'] : '';
        $contact_url = isset( $meta['contact_url'] ) ? (string) $meta['contact_url'] : '';
        $date        = isset( $meta['date'] ) ? (string) $meta['date'] : '';

        $styles = $this->get_base_styles();

        // Document title (browser / PDF metadata).
        $title = 'Website Audit';
        if ( $website_url ) {
            $title .= ' – ' . $website_url;
        }
        if ( $report_type ) {
            $title .= ' (' . $report_type . ')';
        }

        // Header / summary card.
        $header_html  = '<header class="audit-header">';
        $header_html .= '<div class="audit-header-main">';

        // Small generic tag – no explicit "Visitor/Owner report" label.
        $header_html .= '<div class="audit-report-tag">AI Website Audit</div>';

        if ( $website_url ) {
            $header_html .= '<h1 class="audit-title">' . esc_html( $website_url ) . '</h1>';
        } else {
            $header_html .= '<h1 class="audit-title">' . esc_html__( 'Website Audit', 'audit-tool' ) . '</h1>';
        }

        if ( $audit_id ) {
            $header_html .= '<div class="audit-id">Audit ID: ' . esc_html( $audit_id ) . '</div>';
        }

        $header_html .= '</div>';

        // Simple meta table (Date / Prepared for / Contact link / Website).
        $header_html .= '<div class="audit-meta">';
        $header_html .= '<table class="audit-meta-table">';
        if ( $date ) {
            $header_html .= '<tr><th>Date</th><td>' . esc_html( $date ) . '</td></tr>';
        }
        if ( $name ) {
            $header_html .= '<tr><th>Prepared for</th><td>' . esc_html( $name ) . '</td></tr>';
        }
        if ( $contact_url ) {
            $header_html .= '<tr><th>Primary CTA link</th><td><a href="' . esc_url( $contact_url ) . '">' . esc_html( $contact_url ) . '</a></td></tr>';
        }
        if ( $website_url ) {
            $header_html .= '<tr><th>Website</th><td><a href="' . esc_url( $website_url ) . '">' . esc_html( $website_url ) . '</a></td></tr>';
        }
        $header_html .= '</table>';
        $header_html .= '</div>';

        $header_html .= '</header>';

        $html  = '<!DOCTYPE html>';
        $html .= '<html>';
        $html .= '<head>';
        $html .= '<meta charset="utf-8" />';
        $html .= '<title>' . esc_html( $title ) . '</title>';
        $html .= '<style>' . $styles . '</style>';
        $html .= '</head>';
        $html .= '<body>';
        $html .= '<div class="audit-container">';
        $html .= $header_html;
        $html .= '<main class="audit-content">' . $content_html . '</main>';
        $html .= '</div>';
        $html .= '</body>';
        $html .= '</html>';

        return $html;
    }

    /**
     * Load screenshot data and inject per-group screenshots directly under
     * the most relevant headings in the HTML.
     *
     * UX_MESSAGING  screenshots will be placed under UX / Navigation / Messaging / Brand / Trust sections.
     * VISIBILITY    screenshots will be placed under SEO / Blog & Content / Performance & Mobile sections.
     * AUTHORITY     screenshots will be placed under Social / GBP / Reviews / Authority / Legal sections.
     *
     * If we can't find a matching heading for a group, we append that group's block
     * to the end of the content.
     *
     * @param string $html
     * @param array  $meta
     *
     * @return string
     */
    private function inject_group_screenshots_into_html( string $html, array $meta ): string {
        $audit_id = isset( $meta['audit_id'] ) ? trim( (string) $meta['audit_id'] ) : '';
        if ( '' === $audit_id ) {
            return $html;
        }

        $groups = $this->load_screenshot_groups( $audit_id );
        if ( empty( $groups ) ) {
            return $html;
        }

        // Define keyword tokens for each group (all lowercase).
        $group_tokens = [
            'UX_MESSAGING' => [
                'ux',
                'user experience',
                'ui/ux',
                'navigation',
                'menu',
                'journey',
                'homepage',
                'home page',
                'hero',
                'above the fold',
                'copywriting',
                'messaging',
                'value proposition',
                'brand',
                'trust',
                'credibility',
            ],
            'VISIBILITY'   => [
                'seo',
                'search',
                'visibility',
                'organic',
                'keywords',
                'keyword',
                'content',
                'blog',
                'articles',
                'performance',
                'speed',
                'page speed',
                'core web vitals',
                'mobile',
                'mobile experience',
                'responsive',
            ],
            'AUTHORITY'    => [
                'social',
                'social media',
                'social proof',
                'facebook',
                'instagram',
                'tiktok',
                'twitter',
                'x (twitter)',
                'google business',
                'gbp',
                'google maps',
                'maps',
                'reviews',
                'testimonials',
                'reputation',
                'authority',
                'legal',
                'compliance',
                'footer',
                'awards',
                'certifications',
            ],
        ];

        $append_blocks = [];

        foreach ( $group_tokens as $group_id => $tokens ) {
            if ( empty( $groups[ $group_id ] ) ) {
                continue;
            }

            $block_html = $this->build_group_screenshot_block( $groups[ $group_id ] );
            if ( '' === $block_html ) {
                continue;
            }

            $inserted = false;

            // Find all H2/H3 headings once per group on the current HTML snapshot.
            if ( preg_match_all( '/<h([23])[^>]*>(.*?)<\/h\1>/is', $html, $matches, PREG_SET_ORDER | PREG_OFFSET_CAPTURE ) ) {
                foreach ( $matches as $m ) {
                    $full_heading = $m[0][0];
                    $offset       = $m[0][1];
                    $inner_html   = $m[2][0];

                    // Extract inner text and normalise to lowercase.
                    $heading_text = strtolower( trim( wp_strip_all_tags( $inner_html ) ) );
                    if ( '' === $heading_text ) {
                        continue;
                    }

                    // Does this heading contain any of the tokens for this group?
                    foreach ( $tokens as $token ) {
                        $token = strtolower( $token );
                        if ( '' === $token ) {
                            continue;
                        }

                        if ( false !== strpos( $heading_text, $token ) ) {
                            // Insert block immediately after this heading.
                            $insert_pos = $offset + strlen( $full_heading );
                            $html       = substr( $html, 0, $insert_pos ) . $block_html . substr( $html, $insert_pos );
                            $inserted   = true;
                            break 2; // break tokens loop and heading loop.
                        }
                    }
                }
            }

            if ( ! $inserted ) {
                // No suitable heading found; append to the end later.
                $append_blocks[] = $block_html;
            }
        }

        // Append any leftover group blocks at the end of the content.
        foreach ( $append_blocks as $block_html ) {
            $html .= $block_html;
        }

        return $html;
    }

    /**
     * Load screenshots from options and group them by group_id.
     *
     * Returned format:
     * [
     *   'UX_MESSAGING' => [
     *     [ 'id' => 'HOME_HERO', 'image_url' => 'http...', 'purpose' => 'Show hero...' ],
     *     ...
     *   ],
     *   'VISIBILITY'   => [ ... ],
     *   'AUTHORITY'    => [ ... ],
     * ]
     *
     * @param string $audit_id
     *
     * @return array
     */
    private function load_screenshot_groups( string $audit_id ): array {
        $key    = 'audit_tool_screenshots_' . $audit_id;
        $stored = get_option( $key, [] );

        if ( ! is_array( $stored ) || empty( $stored ) ) {
            return [];
        }

        $groups = [];

        foreach ( $stored as $shot_id => $info ) {
            if ( empty( $info['image_url'] ) ) {
                continue;
            }

            $meta_shot = isset( $info['meta']['shot'] ) && is_array( $info['meta']['shot'] )
                ? $info['meta']['shot']
                : [];

            $group_id = isset( $meta_shot['group_id'] ) ? (string) $meta_shot['group_id'] : '';
            if ( '' === $group_id ) {
                continue;
            }

            $groups[ $group_id ][] = [
                'id'        => (string) $shot_id,
                'image_url' => (string) $info['image_url'],
                'purpose'   => isset( $meta_shot['purpose'] ) ? (string) $meta_shot['purpose'] : '',
            ];
        }

        return $groups;
    }

    /**
     * Build a compact screenshot block for a single group (UX / VISIBILITY / AUTHORITY).
     *
     * @param array $shots
     *
     * @return string
     */
    private function build_group_screenshot_block( array $shots ): string {
        if ( empty( $shots ) ) {
            return '';
        }

        $items_html = '';

        foreach ( $shots as $shot ) {
            $img_url = esc_url( (string) $shot['image_url'] );
            $caption = $this->normalise_caption(
                isset( $shot['purpose'] ) ? (string) $shot['purpose'] : '',
                isset( $shot['id'] ) ? (string) $shot['id'] : ''
            );

            $items_html .= '<figure class="audit-screenshot">';
            $items_html .= '<img src="' . $img_url . '" alt="' . esc_attr( $caption ) . '" />';
            $items_html .= '<figcaption><div class="audit-screenshot-title">' . esc_html( $caption ) . '</div></figcaption>';
            $items_html .= '</figure>';
        }

        if ( '' === $items_html ) {
            return '';
        }

        $block  = '<div class="audit-group-screenshots">';
        $block .= '<div class="audit-screenshot-grid">';
        $block .= $items_html;
        $block .= '</div>';
        $block .= '</div>';

        return $block;
    }

    /**
     * Take the raw "purpose" text from the screenshot plan and make a friendlier caption.
     *
     * Examples:
     *   "Show the homepage hero section clearly"       -> "Homepage hero section"
     *   "Capture the mobile menu open state"           -> "Mobile menu open state"
     *   "Highlight testimonials carousel on homepage"  -> "Testimonials carousel on homepage"
     *
     * If purpose is empty, fall back to "Screenshot X".
     *
     * @param string $purpose
     * @param string $shot_id
     *
     * @return string
     */
    private function normalise_caption( string $purpose, string $shot_id ): string {
        $purpose = trim( $purpose );

        if ( '' === $purpose ) {
            return 'Screenshot ' . $shot_id;
        }

        // Strip common leading verbs to make it less instructive.
        $patterns = [
            '/^(show|capture|highlight|focus on|zoom in on)\s+/i',
            '/^please\s+/i',
        ];

        foreach ( $patterns as $pattern ) {
            $purpose = preg_replace( $pattern, '', $purpose );
        }

        // Uppercase first letter for neatness.
        $purpose = ltrim( $purpose );
        if ( '' === $purpose ) {
            return 'Screenshot ' . $shot_id;
        }

        return mb_strtoupper( mb_substr( $purpose, 0, 1 ) ) . mb_substr( $purpose, 1 );
    }

    /**
     * Base CSS for the PDF layout.
     *
     * @return string
     */
    private function get_base_styles(): string {
        return <<<CSS
* {
    box-sizing: border-box;
}

body {
    margin: 0;
    padding: 0;
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
    font-size: 13px;
    line-height: 1.5;
    color: #111827;
}

.audit-container {
    padding: 28px 32px;
}

/* Header */

.audit-header {
    display: block;
    padding: 16px 18px;
    border-radius: 8px;
    border: 1px solid #e5e7eb;
    background-color: #f9fafb;
    margin-bottom: 18px;
}

.audit-header-main {
    margin-bottom: 6px;
}

.audit-report-tag {
    display: inline-block;
    padding: 2px 8px;
    border-radius: 999px;
    font-size: 11px;
    font-weight: 600;
    text-transform: uppercase;
    letter-spacing: 0.04em;
    background-color: #e5e7eb;
    color: #374151;
    margin-bottom: 4px;
}

.audit-title {
    font-size: 18px;
    margin: 0 0 2px 0;
}

.audit-id {
    font-size: 11px;
    color: #6b7280;
}

.audit-meta {
    margin-top: 4px;
}

.audit-meta-table {
    width: 100%;
    border-collapse: collapse;
    font-size: 12px;
}

.audit-meta-table th {
    text-align: left;
    white-space: nowrap;
    padding: 2px 8px 2px 0;
    font-weight: 600;
    color: #374151;
}

.audit-meta-table td {
    padding: 2px 0;
    color: #111827;
}

.audit-meta-table a {
    color: #111827;
    text-decoration: none;
}

/* Main content */

.audit-content {
    margin-top: 16px;
}

.audit-content h1,
.audit-content h2,
.audit-content h3,
.audit-content h4 {
    font-weight: 600;
    color: #111827;
    margin-top: 18px;
    margin-bottom: 6px;
}

.audit-content h1 {
    font-size: 18px;
}

.audit-content h2 {
    font-size: 16px;
}

.audit-content h3 {
    font-size: 14px;
}

.audit-content h4 {
    font-size: 13px;
}

.audit-content p {
    margin: 6px 0 8px 0;
}

.audit-content ul,
.audit-content ol {
    margin: 4px 0 8px 18px;
    padding-left: 18px;
}

.audit-content li {
    margin: 2px 0 2px 0;
}

/* Inline images (if Markdown includes any) */

.audit-content img {
    display: block;
    max-width: 100%;
    height: auto;
    margin: 4px 0 6px 0;
    page-break-inside: avoid;
}

/* Tables */

.audit-content table {
    border-collapse: collapse;
    width: 100%;
    margin: 10px 0 14px 0;
    font-size: 12px;
}

.audit-content table th,
.audit-content table td {
    border: 1px solid #e5e7eb;
    padding: 4px 6px;
}

.audit-content table th {
    background-color: #f3f4f6;
    font-weight: 600;
}

/* Category score badges */

.category-score {
    margin: 4px 0 6px 0;
    page-break-inside: avoid;
}

.category-score-badge,
.category-impact-badge {
    display: inline-block;
    padding: 2px 8px;
    border-radius: 999px;
    font-size: 11px;
    margin-right: 4px;
    margin-bottom: 2px;
}

.category-score-badge {
    border: 1px solid #9ca3af;
    background-color: #f9fafb;
    color: #111827;
}

.category-impact-badge {
    border: 1px solid #f97316;
    background-color: #fff7ed;
    color: #9a3412;
}

/* Per-category screenshot blocks */

.audit-group-screenshots {
    margin: 8px 0 10px 0;
    page-break-inside: avoid;
}

.audit-screenshot-grid {
    display: flex;
    flex-wrap: wrap;
    gap: 8px;
}

.audit-screenshot {
    flex: 0 0 48%;
    max-width: 48%;
    margin-bottom: 4px;
    page-break-inside: avoid;
}

.audit-screenshot img {
    display: block;
    width: 100%;
    height: auto; /* Keep aspect ratio */
    margin-bottom: 4px;
}

.audit-screenshot-title {
    font-weight: 600;
    font-size: 12px;
    margin-bottom: 2px;
}

/* Links */

a {
    color: #2563eb;
    text-decoration: none;
}

a:hover {
    text-decoration: underline;
}

/* Horizontal rules */

hr {
    border: none;
    border-top: 1px solid #e5e7eb;
    margin: 16px 0;
}
CSS;
    }
}

